experiment:
  name: al300_zno200_0602_mlp
  output_root: experiments
  random_state: 42
  test_size: 0.2

data:
  file_path: data/cleaned/AL300_ZnO200_0602_cleaned.csv
  file_type: csv

features:
  input_cols:
    # - Al_thickness_um
    - B4C_thickness_um
    - W_thickness_um
    - ZnO_thickness_um

target:
  type: spectrum_models
  model_tasks:
    # - model_name: electron_spectrum
    #   output_cols:
    #     - electron_spectrum
    - model_name: proton_spectrum
      output_cols:
        - proton_spectrum

models:
  ResidualMLP:
    hidden_dim: 64
    num_blocks: 2
    dropout: 0.2
    lr: 0.001
    weight_decay: 0.00001
    epochs: 500
    batch_size: 16
    patience: 50

output:
  save_clean_dataset: true
  save_models: true
  save_plots: true
  save_metrics: true
  save_config_copy: true
